name: Release to marketplace

on:
  push:
    branches: [release/*]

jobs:
  publish-marketplace:
    name: Release to marketplace
    runs-on: ubuntu-latest
    environment: Release
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - uses: actions/setup-node@53b83947a5a98c8d113130e565377fae1a50d02f # v6.3.0
        with:
          node-version: '22'
          cache: 'npm'
          cache-dependency-path: package-lock.json
      - run: npm install-test
      - name: Show Dependency Manifest
        run: npm ls -a
      - name: Publish to Visual Studio Marketplace
        uses: HaaLeo/publish-vscode-extension@ca5561daa085dee804bf9f37fe0165785a9b14db # v2.0.0
        with:
          pat: ${{ secrets.MICROSOFT_MARKETPLACE_TOKEN }}
          registryUrl: https://marketplace.visualstudio.com
      - name: Publish to Open VSX Registry
        uses: HaaLeo/publish-vscode-extension@ca5561daa085dee804bf9f37fe0165785a9b14db # v2.0.0
        with:
          pat: ${{ secrets.OPEN_VSX_TOKEN }}
